### ISSUE TITLE
XOM Editor not working in VS2022

### ISSUE THREAD

**Issue by cagarraway** [Xomega-Net/Xomega.Net4VS#18]
I'm trying to follow the AdventureWorks walkthrough, using Visual Studio 2022 Community (v17.7.5). When I opened the sales order header.xom file as requested, it shows almost like a normal text file, without any highlighting, collapsible regions, etc. 

<img width="609" alt="image" src="https://github.com/Xomega-Net/Xomega.Net4VS/assets/9914000/207df5d6-0965-4af9-a244-ace7814b7c52">

I thought I'd ignore it, and go old school, but then the walkthrough said to right-click and refactor by renaming an object type, which is not available because the editor isn't working. What has gone wrong?

**Comment by XomegaNet** [comment]
Thanks for reporting this. Does closing and reopening the file help? If not, can you right-click on the file and select the "Open With..." menu? Is Xomega Editor an option there?

**Comment by cagarraway** [comment]
Hahaha, the old restart things trick. I must be sleepy; I didn't think to try that. It's worked BTW. Perhaps the editor was just really slow at loading or something.

<img width="623" alt="image" src="https://github.com/Xomega-Net/Xomega.Net4VS/assets/9914000/89dfd60c-0e4f-423c-a0d6-84b695f84863">
